package transcript

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

// TestRestoreSlashCommand covers the <command-args> recovery fix at the
// parser level. claude expands a human-typed custom command (skill / user
// command) into ONE user line wrapping <command-message>/<command-name>/
// <command-args> — the typed words survive only inside <command-args>. Before
// this fix the whole line was dropped as tooling noise (isCommandEcho matched
// on the wrapper prefix), silently eating the round: no user_intent, and
// turn_count undercounted. Cases below are lifted verbatim from a real claude
// jsonl (kept anonymized-safe: they're the requester's own prior debugging
// text) to pin the fix against the actual production shape, not a guess at it.
func TestRestoreSlashCommand(t *testing.T) {
	cases := []struct {
		name     string
		text     string
		wantOK   bool
		wantText string
	}{
		{
			// Real sample: <command-message> before <command-name>, no indentation.
			name: "real /cw-clarify sample recovers /name + args",
			text: "<command-message>cw-clarify</command-message>\n" +
				"<command-name>/cw-clarify</command-name>\n" +
				"<command-args>我发现一个问题, 问题1, 我明明是在 http://stwork:8080/ws/7/s/311 中调用的,结果提示\"外部cli在跑\"</command-args>",
			wantOK:   true,
			wantText: `/cw-clarify 我发现一个问题, 问题1, 我明明是在 http://stwork:8080/ws/7/s/311 中调用的,结果提示"外部cli在跑"`,
		},
		{
			// Real sample: <command-name> before <command-message>, indented,
			// and <command-args> empty — a real command, but nothing the human
			// typed to recover (/compact takes no argument). Must stay dropped.
			name: "real /compact sample, empty args stays dropped",
			text: "<command-name>/compact</command-name>\n            " +
				"<command-message>compact</command-message>\n            " +
				"<command-args></command-args>",
			wantOK: false,
		},
		{
			// Tags reordered (args first), attributes on the tag, and
			// multi-line/indented content inside <command-args> — the fix must
			// locate each tag independently, not by a fixed offset or order.
			name: "reordered tags + attributes + multiline args still extract",
			text: "  <command-args>\n  multi\n  line   args here  \n</command-args>\n" +
				`<command-name label="x">/weird-cmd</command-name>` + "\n" +
				"<command-message>weird-cmd</command-message>",
			wantOK:   true,
			wantText: "/weird-cmd multi\n  line   args here",
		},
		{
			name:   "plain human text is not a wrapper at all",
			text:   "帮我看一下这个 bug",
			wantOK: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := restoreSlashCommand(tc.text)
			if ok != tc.wantOK {
				t.Fatalf("ok = %v, want %v (got text %q)", ok, tc.wantOK, got)
			}
			if ok && got != tc.wantText {
				t.Fatalf("text = %q, want %q", got, tc.wantText)
			}
		})
	}
}

// TestUnwrapCommandEcho exercises the actual gate every call site now uses.
// Ordinary text passes through untouched; a restorable wrapper becomes
// "/name args"; every other noise shape — <local-command-stdout>, a bare
// Caveat notice, or a wrapper with empty args — still resolves to "" (dropped).
func TestUnwrapCommandEcho(t *testing.T) {
	cases := []struct {
		name string
		text string
		want string
	}{
		{
			name: "recoverable slash command",
			text: "<command-message>cw-brainstorm</command-message>\n" +
				"<command-name>/cw-brainstorm</command-name>\n" +
				"<command-args>你认为最优解是什么?</command-args>",
			want: "/cw-brainstorm 你认为最优解是什么?",
		},
		{
			name: "local-command-stdout echo stays dropped",
			text: "<local-command-stdout>some tool output</local-command-stdout>",
			want: "",
		},
		{
			name: "Caveat notice stays dropped",
			text: "Caveat: The messages below were generated by the user while running local commands.",
			want: "",
		},
		{
			name: "empty-args /compact stays dropped",
			text: "<command-name>/compact</command-name>\n            " +
				"<command-message>compact</command-message>\n            " +
				"<command-args></command-args>",
			want: "",
		},
		{
			name: "plain user text passes through unchanged",
			text: "接下来请继续",
			want: "接下来请继续",
		},
		{
			name: "empty string passes through unchanged",
			text: "",
			want: "",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := unwrapCommandEcho(tc.text); got != tc.want {
				t.Fatalf("unwrapCommandEcho(%q) = %q, want %q", tc.text, got, tc.want)
			}
		})
	}
}

// TestClaudeSlashCommandTurnRestored is the end-to-end proof that all three
// call sites benefit, not just the parser: a synthetic jsonl carrying a real
// /cw-clarify envelope must (1) render as a normal user bubble (appendUserTurn,
// claude.go:414/422) AND (2) count as one human turn / drive the session title
// (scanMeta, claude.go:161) — while a plain follow-up turn and the model's
// end_turn boundary still behave exactly as before (regression guard).
func TestClaudeSlashCommandTurnRestored(t *testing.T) {
	dir := t.TempDir()
	projects := filepath.Join(dir, "projects")
	projectDir := "/fake/proj-cmdecho"
	encDir := filepath.Join(projects, EncodeProjectDir(projectDir))
	if err := os.MkdirAll(encDir, 0o755); err != nil {
		t.Fatal(err)
	}

	jsonl := `{"type":"user","timestamp":"2026-07-19T09:39:18.403Z","message":{"role":"user","content":"<command-message>cw-clarify</command-message>\n<command-name>/cw-clarify</command-name>\n<command-args>我发现一个问题，请帮忙看看</command-args>"}}
{"type":"assistant","timestamp":"2026-07-19T09:39:20.000Z","message":{"id":"msg_1","model":"claude-x","content":[{"type":"text","text":"好的，我来看看"}],"stop_reason":"end_turn"}}
{"type":"user","timestamp":"2026-07-19T09:40:00.000Z","message":{"role":"user","content":"谢谢"}}
`
	id := "session-cmdecho"
	path := filepath.Join(encDir, id+".jsonl")
	if err := os.WriteFile(path, []byte(jsonl), 0o644); err != nil {
		t.Fatal(err)
	}

	src := &ClaudeSource{Root: projects}
	wantFirst := "/cw-clarify 我发现一个问题，请帮忙看看"

	// Call sites 2+3 (appendUserTurn: bubble assembly + accept/reject gate).
	tr, err := src.LoadTranscript(context.Background(), SessionRef{ProjectDir: projectDir, ID: id})
	if err != nil {
		t.Fatalf("LoadTranscript: %v", err)
	}
	var userTexts []string
	for ti := range tr.Turns {
		for bi := range tr.Turns[ti].Blocks {
			if b := tr.Turns[ti].Blocks[bi]; b.Type == BlockUser {
				userTexts = append(userTexts, b.Text)
			}
		}
	}
	if len(userTexts) != 2 || userTexts[0] != wantFirst || userTexts[1] != "谢谢" {
		t.Fatalf("user bubbles = %#v, want [%q %q]", userTexts, wantFirst, "谢谢")
	}

	// Call site 1 (scanMeta: turn_count + title fallback).
	meta := src.scanMeta(path, id)
	if meta.TurnCount != 2 {
		t.Fatalf("TurnCount = %d, want 2 (restored /cw-clarify turn + 谢谢)", meta.TurnCount)
	}
	if meta.Title != wantFirst {
		t.Fatalf("Title = %q, want %q (first-user-text fallback)", meta.Title, wantFirst)
	}
}
